### ISSUE TITLE
Port release-2.x plugins to 3.0 API

### ISSUE THREAD

**Issue by kxz** [kxz/omnipresence#2]
- [ ] `amazon`
- [x] `autorejoin`
- [x] `autovoice`
- [ ] `chanlog` (also see #9)
- [ ] `chirpy`
- [ ] `lastfm`
- [x] `mstranslate`
- [ ] `nickserv`
- [ ] `peak` (also see #9)
- [x] ~~`rottentomatoes`~~ API is being turned down
- [ ] `rss`
- [ ] `seen` (also see #9)
- [ ] `topic`
- [ ] `trace` (also see #9)
- [x] `url` (also see #1)
- [ ] `wikipedia`
- [ ] `wolframalpha`
- [ ] `youtube`
